-- ==========================================================
-- TAREA 2: ADMINISTRACION DE BASES DE DATOS Y OPERACIONES CRUD
-- Nombre: NEYTAN ELIAS MORALES GARCIA
-- Carnet: 1890-24-4168
-- ==========================================================

/*==========================================================
  PASO 1: CREACION DE TABLESPACES Y USUARIOS
  EJECUTAR COMO SYS EN FREEPDB1
==========================================================*/

CREATE TABLESPACE TS_TIENDA4168
DATAFILE 'C:\APP\NAYTA\PRODUCT\26AI\ORADATA\FREE\FREEPDB1\TS_TIENDA4168.DBF'
SIZE 15M
AUTOEXTEND ON
NEXT 5M
MAXSIZE UNLIMITED;

CREATE USER DB_TIENDA4168
IDENTIFIED BY tienda123
DEFAULT TABLESPACE TS_TIENDA4168
QUOTA UNLIMITED ON TS_TIENDA4168;

GRANT CONNECT, RESOURCE TO DB_TIENDA4168;


CREATE TABLESPACE TS_ACADEMICO4168
DATAFILE 'C:\APP\NAYTA\PRODUCT\26AI\ORADATA\FREE\FREEPDB1\TS_ACADEMICO4168.DBF'
SIZE 15M
AUTOEXTEND ON
NEXT 5M
MAXSIZE UNLIMITED;

CREATE USER DB_ACADEMICO4168
IDENTIFIED BY academico123
DEFAULT TABLESPACE TS_ACADEMICO4168
QUOTA UNLIMITED ON TS_ACADEMICO4168;

GRANT CONNECT, RESOURCE TO DB_ACADEMICO4168;


CREATE TABLESPACE TS_TALLER4168
DATAFILE 'C:\APP\NAYTA\PRODUCT\26AI\ORADATA\FREE\FREEPDB1\TS_TALLER4168.DBF'
SIZE 15M
AUTOEXTEND ON
NEXT 5M
MAXSIZE UNLIMITED;

CREATE USER DB_TALLER4168
IDENTIFIED BY taller123
DEFAULT TABLESPACE TS_TALLER4168
QUOTA UNLIMITED ON TS_TALLER4168;

GRANT CONNECT, RESOURCE TO DB_TALLER4168;

/*==========================================================
  BASE DE DATOS 1: DB_TIENDA4168
==========================================================*/

CREATE TABLE PRODUCTOS (
    ID NUMBER PRIMARY KEY,
    NOMBRE VARCHAR2(100),
    PRECIO NUMBER(10,2),
    STOCK NUMBER
);

CREATE TABLE CLIENTES (
    ID NUMBER PRIMARY KEY,
    NOMBRE VARCHAR2(100),
    NIT_DPI VARCHAR2(30),
    CORREO VARCHAR2(100)
);

-- INSERT

INSERT INTO PRODUCTOS VALUES (1,'Teclado',500,20);

INSERT INTO CLIENTES VALUES
(2,'Maria Lima','4758936','maria@gmail.com');

-- SELECT

SELECT * FROM PRODUCTOS;
SELECT * FROM CLIENTES;

-- UPDATE

UPDATE PRODUCTOS
SET PRECIO = 100
WHERE ID = 2;

UPDATE CLIENTES
SET NOMBRE = 'Luisa Fernanda Lopez'
WHERE ID = 2;

-- DELETE

DELETE FROM PRODUCTOS
WHERE ID = 1;

DELETE FROM CLIENTES
WHERE ID = 2;

COMMIT;

/*==========================================================
  BASE DE DATOS 2: DB_ACADEMICO4168
==========================================================*/

CREATE TABLE ESTUDIANTES (
    CARNET NUMBER PRIMARY KEY,
    NOMBRE VARCHAR2(100),
    CARRERA VARCHAR2(100)
);

CREATE TABLE CURSOS (
    CODIGO VARCHAR2(20) PRIMARY KEY,
    NOMBRE_CURSO VARCHAR2(100),
    CREDITOS NUMBER
);

-- INSERT

INSERT INTO ESTUDIANTES VALUES
(1002,'Fabiola Lopez','Ingenieria');

INSERT INTO CURSOS VALUES
('MI03','Matematica',5);

-- SELECT

SELECT * FROM ESTUDIANTES;
SELECT * FROM CURSOS;

-- UPDATE

UPDATE ESTUDIANTES
SET NOMBRE = 'Luis Fernando Gomez'
WHERE CARNET = 1002;

UPDATE CURSOS
SET NOMBRE_CURSO = 'Base de Datos'
WHERE CODIGO = 'PRO102';

-- DELETE

DELETE FROM ESTUDIANTES
WHERE CARNET = 1002;

DELETE FROM CURSOS
WHERE CODIGO = 'AI05';

COMMIT;

/*==========================================================
  BASE DE DATOS 3: DB_TALLER4168
==========================================================*/

CREATE TABLE VEHICULOS (
    PLACA VARCHAR2(20) PRIMARY KEY,
    MARCA VARCHAR2(50),
    MODELO VARCHAR2(50),
    ANIO NUMBER
);

CREATE TABLE MECANICOS (
    ID NUMBER PRIMARY KEY,
    NOMBRE VARCHAR2(100),
    ESPECIALIDAD VARCHAR2(100)
);

-- INSERT

INSERT INTO VEHICULOS VALUES
('P189','Toyota','Yaris',2025);

INSERT INTO MECANICOS VALUES
(1,'Sergio Morales','Suspension');

-- SELECT

SELECT * FROM VEHICULOS;
SELECT * FROM MECANICOS;

-- UPDATE

UPDATE VEHICULOS
SET MODELO = 'Tucson'
WHERE PLACA = 'P123ABC';

UPDATE MECANICOS
SET NOMBRE = 'Julio Estrada'
WHERE ID = 2;

-- DELETE

DELETE FROM VEHICULOS
WHERE PLACA = 'P135JKL';

DELETE FROM MECANICOS
WHERE ID = 3;

COMMIT;

-- ==========================================================
-- FIN DEL SCRIPT
-- ==========================================================